GovAlta/ui-components-docs

src/components/component-header/ComponentHeader.tsx
Based on Tom's feedback: we will change the component header's badge to the default type `information`
=> chore: set all component header badge's type to "information"

src/components/component-properties/ComponentProperties.tsx, src/routes/design-tokens/border-radius/BorderRadius.tsx, src/routes/design-tokens/border-width/BorderWidth.tsx, src/routes/design-tokens/color/Color.tsx, src/routes/design-tokens/icon-size/IconSize.tsx, src/routes/design-tokens/opacity/Opacity.tsx, src/routes/design-tokens/shadow/Shadow.tsx, src/routes/design-tokens/spacing/Spacing.tsx, src/routes/design-tokens/typography/Typography.tsx
According to the [feedback](https://goa-dio.slack.com/archives/C05RR2UEJDN/p1699983241072539?thread_ts=1699971811.424419&cid=C05RR2UEJDN), 
our tables in the design website should be 100% width.
=> chore: make table's width 100% - code review needed

src/App.tsx, src/routes/components/Table.tsx
=> feat(#1423): Add table page (code review needed)

src/routes/components/Spacer.tsx
This allows for both the horizontal and vertical properties to be tested individually since they both work when tested together.
=> fix(#1469): split up properties into separate sandboxes

src/routes/components/Details.tsx
helper text updated in example
=> chore: content update

src/App.tsx, src/routes/get-started/GetStartedLayout.tsx
This is being done on request from Mark. The page may be used in the future so it isn't being deleted, but the principles haven't been made official yet, so removing links to this page so people can't view it just yet.
=> chore: Removing links to the Service Principles page

src/routes/root.tsx
Requested by Mark. Logic is for the previous feedback link people need a Github account, which many designers and other non-technical users don't have. This new link provides a more accepted way of getting feedback.
=> chore: Changing the feedback link

src/routes/components/Block.tsx, src/routes/components/ButtonGroup.tsx, src/routes/components/Dropdown.tsx, src/routes/components/Spacer.tsx, src/routes/components/Table.tsx, src/routes/components/TextField.tsx
- [] TextArea (kind of a bug on Textarea, agree to ignore it for now)
=> chore: center components in sandbox - code review needed

src/routes/root.tsx
Follow [bug 1377](https://github.com/GovAlta/ui-components/issues/1377) to fix the website. 
https://github.com/GovAlta/ui-components-docs/assets/120135417/2059ff4c-9649-47e9-a683-eb6a983d853a
=> fix(#1377): make app header collapse when screen size is less than 1140

src/routes/components/AppFooter.tsx
Couple of Text changes for properties section, hide footer's meta property section for React (keep for Angular), and fix the code being generated to include slot="meta/nav" attribute for Angular, but no slot attribute for React.
=> fix(#1681): footer documentation related changes

src/components/sandbox/AngularReactiveSerializer.ts, src/components/sandbox/AngularSerializer.ts, src/components/sandbox/BaseSerializer.ts, src/components/sandbox/ComponentSerializer.ts, src/components/sandbox/ReactSerializer.ts, src/routes/components/Checkbox.tsx
For the checkbox documentation, for the code generated for the Reactive Angular section
-Remove the duplication of [formControl] and [value] attributes
-Use [attr.disabled]="true" when disabled is selected
-Prevent disappearing of attributes when properties are changed e.g. description is provided or disabled is selected, etc.
NOTE: (@lizhuomeng71 @ArakTaiRoth  @vanessatran-ddi)
KEEP goaChecked, remove goaValue...Although, the copy code will not work, but based on the discussion with @chrisolsen this is how it should be.
=> fix(#1586): fix checkbox docs for angular reactive

src/routes/components/DatePicker.tsx
This PR is a fix for https://github.com/GovAlta/ui-components/issues/1645 that adds an `error` property to the date picker page.
It depends on the date picker changes in PR https://github.com/GovAlta/ui-components/pull/1787.
=> fix(#1645): add error property to date picker docs

src/examples/checkbox/CheckboxExamples.tsx, src/examples/radio/RadioExamples.tsx, src/routes/components/Checkbox.tsx, src/routes/components/Radio.tsx
This PR for https://github.com/GovAlta/ui-components/issues/1783 has the following documentation changes to radio and checkbox:
- Adds slot/reactNote type to description property.
- Adds an example of a component as a description. (Based on this [Figma example](https://www.figma.com/file/aIRjvBzpIUH0GbkffjbL04/%E2%9D%96-Patterns-library-%7C-DDD?type=design&node-id=1896-179623&mode=design&t=SirlL7cnXiEtQMJE-4))
- Cleans up the other property descriptions and ensures they all end in a period
=> docs(#1783): radio and checkbox slot description and example

src/components/component-content/ComponentContent.tsx, src/components/component-content/component-content.css, src/routes/content/Capitalization.tsx, src/routes/content/DateFormat.tsx, src/routes/content/ErrorMessages.tsx, src/routes/content/HelperText.tsx
This PR addresses the issues identified in https://github.com/GovAlta/ui-components/issues/1803. It makes the following changes:
- Reduces the minimum grid width of the "Do &  Don't" columns from `50ch` to `36ch`
- Swiches the `ComponentContent` grid to a single column when the table of contents disappears below `1230px` width.
- Adds a `min-width` of 0 to `.component-content--content`. This prevents wider content from [growing the column width past the available space](https://css-tricks.com/preventing-a-grid-blowout/).
- Fixes an `undefined` class name in `ComponentContent`
I determined that `36ch` is the maximum width at `642px` without overflowing the content area.
The header-related issues are captured in this other ticket: https://github.com/GovAlta/ui-components/issues/1438 …
=> fix(#1803): fix do/don't grids and component content grid

package-lock.json, package.json, src/routes/components/Container.tsx
This PR documents the change from PR https://github.com/GovAlta/ui-components/pull/1851 for issue https://github.com/GovAlta/ui-components/issues/1816. It includes the following changes:
- Adds `Width` property to container playground
- Adds `Width` property description
- Fixes punctuation and spelling for other container property descriptions.
=> feat(#1816): width property for container

package-lock.json, package.json, src/routes/components/Icons.tsx
This PR documents the following properties on the `icon` component:
- opacity
- fill colour
- inverted
- title
- aria label
It also adds controls for the above properties to the sandbox:
=> fix(#1605): document additional icon properties

package-lock.json, package.json, src/routes/components/Popover.tsx
Following issue #1713 https://github.com/GovAlta/ui-components/issues/1713 and document it, add `minWidth` for Popover component.
=> chore(#1713): add maxWidth to Popover properties table

src/routes/components/TextField.tsx
=> fix(#1847): documentation - add keypress to props for input(textfield)

package-lock.json, package.json, src/routes/components/Accordion.tsx, src/routes/components/Callout.tsx, src/routes/components/Checkbox.tsx, src/routes/components/Container.tsx, src/routes/components/Details.tsx, src/routes/components/FormItemPage.tsx, src/routes/components/Popover.tsx, src/routes/components/Radio.tsx
Documents the `maxwidth` property added to the following components:
- Accordion
- Callout
- Checkbox
- Container
- Details
- Form item
- Radio item
This documents the changes from https://github.com/GovAlta/ui-components/pull/1956.
=> feat(#1797): document max width on components

src/examples/radio/RadioExamples.tsx, src/routes/components/Radio.tsx
This PR makes the following changes:
1. Removes the `maxwidth` from the sandbox. The sandbox is for the radio group, not individual radio items.
2. Adds an example with `maxwidth` on a radio item.
=> fix(#1797): remove radio maxwidth sandbox and add example

src/index.css
`<h3>` tags on the website should now continue to use the proper font style, `--goa-typography-heading-m` even in mobile.
=> fix(#2026): Remove mobile h3 CSS

src/routes/components/TextArea.tsx
1. Show Count option was available in the sandbox
2. For React sandbox code, `onChange` was listed as such
1. Show Count option should no longer exist
2. For React sandbox code, `onChange` should be `function onChange`
=> fix(#2048): Modified TextArea Sandbox

package-lock.json, package.json, src/routes/components/Chip.tsx
There should be a new property called `icontheme` or `iconTheme` added to the Chip component sandbox and Property Accordion.
=> feat(#2080): Added icon theme prop to Chip component

src/routes/components/Skeleton.tsx
=> fix(#2097): docs skeleton props update for Angular and React

src/routes/get-started/designers/UxDesigner.tsx
On this [page](http://localhost:5173/get-started/designers). The following links should be changed:
1. "starter template file" should go to https://www.figma.com/design/l5kjG0bfltQFqPpK2uorC0/DDD-Figma-file-template?m=auto&t=1Stq1DIiLM6zOVqf-6
2. "helper components" should go to https://www.figma.com/design/TDbVPfpFxcUj4iuaJf7a0V/%E2%9D%96-Low-Fi-Prototyping-%26-Annotation-Kit-%7C-DDD?node-id=1101-7241&t=bnms7IudBx2gX3Rx-1
=> fix(#2061): Changed links on Designer get started page

package-lock.json, package.json, src/routes/components/MicrositeHeader.tsx
-documentation updates for MicroSiteHeader
-new example for custom click event handler for the feedback
=> fix(#1897): docs microsite header feedback click handler

src/routes/components/TextArea.tsx
Text Area sandbox should no longer have the `width` option
=> fix(#2055): Removed width option from TextArea sandbox

src/examples/modal/ModalExamples.tsx, src/routes/components/Modal.tsx
Updated the top margin on the action buttons for the Modal in the sandbox. And removed top margin from the buttons for example "Warn a user of a deadline"
=> fix(#2069): Updated top margin on modal buttons

src/routes/components/DatePicker.tsx
Code under Date Picker Reactive Forms example:
```javascript
import { FormControl } from "@angular/forms";
export class MyComponent {
reactiveFormCtrl = new FormControl(new Date());
}
```
Code under Date Picker Reactive Forms example:
```javascript
import { FormControl } from "@angular/forms";
export class MyComponent {
itemFormCtrl = new FormControl(new Date());
}
```
=> fix(#2161): Update Angular DatePicker sandbox code

src/examples/dropdown/DropdownExamples.tsx
Documentation example for the edge case. 
This is related to story [#2114](https://github.com/GovAlta/ui-components/issues/2114). There was no code change required, just needed an example for this specific scenario...using "key" and "mount" props
Figma Url: https://www.figma.com/design/aeIJGExcpx9ecqnIVwImi1/Component-Pages?t=tskpTCe0RrQSgyDi-0
Figma Screenshot (for this example)
Refer to the video in the comments under PR https://github.com/GovAlta/ui-components/pull/2165.
=> fix(#2114): docs dropdown edge case example

src/examples/microsite-header/MicrositeHeaderExamples.tsx, src/routes/components/MicrositeHeader.tsx
This PR documents the changes from https://github.com/GovAlta/ui-components/pull/2086.
=> feat(#2053): allow slotted content in microsite header version

src/routes/get-started/ReportBug.tsx
In the screen Get Started --> Support --> Report a Bug the versions listed should now be pulled down via an API call instead of statically entered.
=> fix(#2239): Updated package versions to use NPM API

src/routes/get-started/developers/DevelopersSetup.tsx
We have `lts` tag for the current production version. I update the Developers Setup guide to make sure ppl install `lts` version, instead of `latest`, so they won't automatically install a breaking change/major version if they don't feel ready. 
This only applies for `angular-components` and `react-components`
=> chore(#2329): update the guide to install lts version

src/routes/get-started/UserExperienceGuidelines.tsx
Updated URLs linked to the SharePoint site on User Experience Guidelines page as the current ones lead to a 404.
From: 
To:
=> chore: update links in the User Experience Guidelines page

src/routes/get-started/ReportBug.tsx
This needs to be tested. To test, create a bug using the Report Bug feature on the website. Then take a look at the created bug in Github issues.
1. No more bug label should exist
2. The type should be set to Bug
This may not work, I suspect it might also need an update to the token used, but I don't know.
=> chore: Updating Report Bug Github API call

src/components/version-language-switcher/VersionLanguageSwitcher.tsx
Popover can be closed by ~blurring parent element~ changing the url and it works in all major browsers
<video src="https://github.com/user-attachments/assets/f5c4714e-9090-4982-aa87-571522a7368f" width="200"></video>
=> fix(#2397): popover close

src/routes/patterns/PatternsLayout.tsx, src/routes/patterns/PatternsOverview.tsx, src/routes/patterns/PublicFormPage.tsx, src/versioned-router.tsx
All references to Simple form should be changed to Public form, including filenames and links.
=> fix(#2577): Change all references to Simple Form to Public Form

src/routes/get-started/Contribute.tsx
Updated the contribution documentation.
Changed the commands required to run the various playground environments. Added info about Angular wrappers and their locations. Updated testing procedures (what tests to run, who will manually test, etc...).
=> fix(#2470): Updated Contribution documentation

src/routes/get-started/ReportBug.tsx
Stackblitz links for both the Angular and React templates are now available in the help text of the Stackblitz URL Form Item.
=> feat(#2500): Added Stackblitz links to Bug Report form

src/examples/link/LinkExamples.tsx, src/routes/components/AllComponents.tsx, src/routes/components/Components.tsx, src/routes/components/Link.tsx, src/versioned-router.tsx
This PR adds documentation for the Link component which now works with our `alpha` Angular and React components. (Implemented in https://github.com/GovAlta/ui-components/issues/2522)
=> feat(#2594): document link component

src/examples/checkbox/CheckboxDescriptionExample.tsx, src/examples/checkbox/CheckboxExamples.tsx, src/examples/checkbox/CheckboxNoneOrManyExample.tsx, src/routes/components/Checkbox.tsx
This PR adds a checkbox example for selecting one, any or all items.
=> feat(#2129): add none or many checkbox example

src/examples/notification/NotificationExamples.tsx, src/examples/notification/NotificationServiceOutageExample.tsx, src/routes/components/Notificationbanner.tsx
This PR adds an example for our notification banner component.
I used a generic example email since this page is visible to the public.
=> feat(#2122): add notification outage example

src/components/sandbox/Sandbox.css, src/components/sandbox/Sandbox.tsx, src/examples/modal/ModalWarnUserDeadlineExample.tsx
- Added properties and styling to sandbox note to be able to use a callout or basic text
- Added callout note to ["Warn user of a deadline" example](https://deploy-preview-351--abgov-ui-component-docs.netlify.app/components/modal#tab-1) on Modal component page
```
<Sandbox
note={{
type: "important",
heading: "AlertDialog Accessibility",
content: "Do not make the modal closeable or add any focusable elements before the action button when using an AlertDialog. This ensures that the screen reader will announce the full content."
}}>
```
```
<Sandbox
note={
"Do not make the modal closeable or add any focusable elements before the action button when using an AlertDialog. This ensures that the screen reader will announce the full content."
}>
```
=> feat: style of sandbox note

package-lock.json, package.json, src/App.tsx, src/routes/get-started/GetStartedLayout.tsx, src/routes/get-started/LtsPolicyPage.tsx, src/routes/get-started/developers/upgrade-guide/DevelopersUpgrade.tsx
Figma: https://www.figma.com/design/RyTquYiWr8x3Ecq7jqHYZK/Version-update-guide-update-and-LTS-page?node-id=1-15108&m=dev
=> feat(#2629): add lts policy page

src/examples/textarea/TextAreaAskLongQuestionExample.tsx, src/examples/textarea/TextAreaExamples.tsx, src/routes/components/TextArea.tsx
This PR adds a  `textarea` example for asking a question with a long response.
=> feat(#2136): add textarea example for long question

src/routes/components/Icons.tsx, src/routes/get-started/Contribute.tsx, src/routes/get-started/GetStartedLayout.tsx, src/routes/get-started/GetStartedOverview.tsx, src/routes/get-started/LtsPolicyPage.tsx, src/routes/get-started/ReportBug.tsx, src/routes/get-started/RequestFeature.tsx, src/routes/get-started/Roadmap.tsx, src/routes/get-started/Support.tsx, src/routes/get-started/UserExperienceGuidelines.tsx, src/routes/get-started/designers/UxDesigner.tsx, src/routes/get-started/developers/BugVerification.tsx, src/routes/get-started/developers/DevelopersOverview.tsx, src/routes/get-started/developers/DevelopersSetup.tsx, src/routes/get-started/developers/DevelopersTechnologies.tsx, src/routes/get-started/developers/DevelopersVSCode.tsx, src/routes/get-started/developers/SupportedBrowsers.tsx, src/routes/get-started/developers/upgrade-guide/AngularGuide.tsx, src/routes/get-started/developers/upgrade-guide/DevelopersUpgrade.tsx, src/routes/get-started/developers/upgrade-guide/ReactGuide.tsx, src/routes/get-started/qa-testing/QATestingOverview.tsx
Update roadmap content as per this issue:
https://github.com/GovAlta/ui-components/issues/2487
Also updated all Get-Started content pages to use GoabText component for better spacing, line length, and consistency going forward.
=> feat (#2487): Roadmap content update

src/examples/pagination/PaginationExamples.tsx
Change label of example from "Show # results per page" to "Set items per page and navigate multiple pages in a table"
From: 
To:
=> feat(#2301): pagination - change example label

src/routes/get-started/developers/upgrade-guide/components.ts
Story https://github.com/GovAlta/ui-components/issues/2764
=> fix(#2764): docs mistype in upgrade guide

package-lock.json, package.json, src/components/old-component-banner/OldComponentBanner.tsx, src/examples/checkbox/CheckboxExamples.tsx, src/examples/checkbox/CheckboxRevealSlotExample.tsx, src/examples/radio/RadioExamples.tsx, src/examples/radio/RadioRevealSlotExample.tsx, src/routes/components/Checkbox.tsx, src/routes/components/Radio.tsx
Figma link: https://www.figma.com/design/aIRjvBzpIUH0GbkffjbL04/%E2%9D%96-Patterns-library-%7C-DDD?node-id=6307-131069&t=x1s3J4yJHbyp8BNX-4
=> feat(#2532): add radio/checkbox reveal slot example 

src/components/version-language-switcher/HelpButton.tsx, src/components/version-language-switcher/VersionLanguageSwitcher.tsx, src/components/version-language-switcher/version-language-switcher.css
=> Bug fix: mobile language switcher controls breaking on mobile

src/examples/badge/BadgeExamples.tsx, src/examples/display-numbers-in-a-table-so-they-can-be-scanned-easily.tsx, src/examples/hero-banner-with-actions.tsx, src/examples/hero-banner/HeroBannerExamples.tsx, src/examples/icon-button/IconButtonExamples.tsx, src/examples/show-multiple-actions-in-a-compact-table.tsx, src/examples/show-multiple-tags-together.tsx, src/examples/sort-data-in-a-table.tsx, src/examples/tables/TablesExamples.tsx, src/routes/components/HeroBanner.tsx, src/routes/components/IconButton.tsx, src/routes/components/Table.tsx
Moved examples for components: table, hero-banner, icon-button, badge
=> task(#2898): move components examples

src/components/table-of-contents/TOC.tsx, src/routes/components/Skeleton.tsx
Resolves: [2835](https://github.com/GovAlta/ui-components/issues/2835)
=> fix(#2835): skeleton all section links

src/examples/basic-modal-with-close.tsx, src/examples/icon-button/IconButtonExamples.tsx, src/routes/components/IconButton.tsx
For Icon Button component page, added the "Basic modal with close" example. For this, reused the "require-user-action-before-continuing.tsx" example as it has the close button.
=> feat(#2134): icon button - added "Basic modal with close" example

src/examples/choose-a-date.tsx, src/examples/date-picker/DatePickerExamples.tsx, src/examples/reset-date-picker-field.tsx, src/routes/components/DatePicker.tsx
Added the "Choose a date" example (including the React and Angular):
In addition, adjusted how the code displays for the "Reset" example.
=> feat(#2131): date picker - added "Choose a date" example

src/examples/ask-a-user-for-direct-deposit-information.tsx, src/examples/show-a-list-to-help-answer-a-question.tsx
Added margin-top values of xl to two Details examples:
- "Show a list to help answer a question"
- "Ask a user for direct deposit information"
=> feat(#2300): details - adjusted margins in examples

src/examples/basic-question-page-with-a-dropdown.tsx, src/examples/choose-one-option-from-a-list.tsx, src/examples/dropdown/DropdownExamples.tsx, src/examples/filter-through-long-list-to-choose-an-option.tsx, src/routes/components/Dropdown.tsx
Added the following examples to the dropdown page:
- Choose one option from a list
- Filter through a long list to choose an option
- Basic question page
=> feat(#2132): drop down - added more contextual examples

.github/copilot-instructions.md
This PR adds initial instruction files for GitHub Copilot to use. Topics include...
- How our documentation pages are structured
- How we show the LTS version of documentation
- How we write commits and pull requests
I've created a test PR using these instruction files: https://github.com/GovAlta/ui-components/issues/2801
These instruction files will guide Copilot in the `ui-components-docs` repo both locally and online. We can continue to update them as we learn.
I've kept the instructions brief to align with the guidelines:
> The instructions you add to your custom instruction file(s) should be short, self-contained statements that provide Copilot with relevant information to help it work in this repository. Because the instructions are sent with every chat message, they should be …
=> chore(#2966): Add initial Copilot instructions

src/examples/display-numbers-in-a-table-so-they-can-be-scanned-easily.tsx, src/examples/filter-data-in-a-table.tsx, src/examples/tables/TablesExamples.tsx, src/examples/tables/tables-page-examples.css, src/examples/zebra-stripes-in-a-table.tsx, src/routes/components/Table.tsx
**Added the following example:**
- _Zebra Stripes_
**Modified the following examples:**
- _Table with filters_ -- Combined filtering through text input with filtering with radio buttons. "Filter" button now makes popover appear. Text input filtering actions through the Enter key
-_Display numbers in a table so they can be scanned easily_ -- In the Issue ticket, it was noted that this one should be removed. However, with the example on the Figma file, I kept it in. Please confirm if this should be kept or not.
=> feat(#2120): table - added and modified contextual examples
