GovAlta/ui-components-docs

- src/components/do-dont/DoDont.css
- src/components/do-dont/DoDont.tsx
- src/routes/components/Checkbox.tsx
> fix(#1134): Add Do Don't component

- .prettierrc
- src/components/code-snippet/CodeSnippet.css
- src/components/code-snippet/CodeSnippet.tsx
- src/components/component-card/ComponentCard.css
- src/components/component-header/ComponentHeader.css
- src/components/component-header/ComponentHeader.tsx
- src/components/component-properties/ComponentProperties.tsx
- src/components/sandbox/Sandbox.css
- src/components/sandbox/Sandbox.tsx
- src/components/sandbox/SandboxProperties.tsx
- src/components/support-info/SupportInfo.css
- src/components/token-snippet/TokenSnippet.css
- src/routes/components/AllComponents.tsx
- src/routes/components/Button.tsx
- src/routes/components/Components.tsx
- src/routes/components/Dropdown.tsx
- src/routes/design-tokens/DesignToken.css
- src/routes/design-tokens/DesignTokenLayout.tsx
- src/routes/root.css
- src/routes/root.tsx
Buttons page: (Not including design guidelines)
> feat(#1325): Buttons page

- src/App.tsx
- src/components/component-properties/ComponentProperties.tsx
- src/routes/components/Accordion.tsx
- src/routes/components/Components.tsx
> feat(new-accordion-page): Add accordion page.

- src/App.tsx
- src/routes/components/Badge.tsx
> feat(badge): Add badge component page

- package-lock.json
- package.json
- src/App.tsx
- src/routes/components/Skeleton.tsx
> feat: Add skeleton page

- src/App.tsx
- src/routes/components/HeroBanner.tsx
> feat(#1423): Add hero-banner page - Code review needed

- src/App.tsx
- src/components/component-properties/ComponentProperties.tsx
- src/routes/components/Divider.tsx
> feat(#1423): Add divider page (Code review needed)

- src/App.tsx
- src/routes/components/Spacer.tsx
> feat(#1427): Add spacer page

- src/App.tsx
- src/routes/components/Block.tsx
> feat(#1427): Add block page

- src/App.tsx
- src/routes/components/Grid.tsx
> feat(#1427): Add grid page

- src/App.tsx
- src/routes/components/ButtonGroup.tsx
- src/routes/components/Components.tsx
> feat(#1425): Add Button Group page - Ready for code review

- src/routes/components/Checkbox.tsx
> feat(#1425): Add checkbox page (Ready for code review)

- src/components/component-properties/ComponentProperties.tsx
- src/components/sandbox/Sandbox.tsx
- src/routes/components/Components.tsx
- src/routes/components/Dropdown.tsx
> feat(#1425): Add dropdown page - Code review needed

- src/App.tsx
- src/routes/components/FileUploader.tsx
> feat(#1425): Add FileUploader page - Code review needed

- src/App.tsx
- src/routes/components/FormItemPage.tsx
> feat(#1425): add FormItem page - Need code review

- src/App.tsx
- src/routes/components/Radio.tsx
> feat(#1425): Add Radio page - Code review needed

- src/App.tsx
- src/routes/patterns/LayoutPage.tsx
- src/routes/patterns/PatternsLayout.tsx
Add patterns layout page
Screenshot:
> feat(#1375): Add patterns layout page - Code review needed

- src/App.tsx
- src/routes/components/TextField.tsx
> feat(#1425): Add TextField page - Code review needed

- src/components/sandbox/AngularSerializer.ts
Issue is described at https://github.com/GovAlta/ui-components/issues/1487
> fix(#1487): sandbox - CodeSnippet - render for Angular code - boolean should be put inside "" - Code review needed

- package-lock.json
- package.json
- src/App.tsx
- src/components/sandbox/ComponentBinding.ts
- src/routes/components/TextArea.tsx
> feat(#1425): Add Textarea page - Code review needed

- src/routes/components/Accordion.tsx
- src/routes/components/Button.tsx
- src/routes/components/Checkbox.tsx
- src/routes/components/Components.tsx
- src/routes/components/Container.tsx
- src/routes/components/Dropdown.tsx
- src/routes/components/FileUploader.tsx
- src/routes/components/Radio.tsx
- src/routes/components/Skeleton.tsx
- src/routes/components/TextArea.tsx
- src/routes/components/TextField.tsx
Ticket: https://github.com/GovAlta/ui-components/issues/1420
Fixing some code that is not rendered correctly.
> fix(#1420): fix some code snippet errors - Code review needed

- src/routes/components/Block.tsx
> chore(#1526): block sandbox example - alignment direction row

- src/routes/home.tsx
> chore: Update home.tsx

- src/routes/components/Button.tsx
changing content to test commit and PR
> chore: Update Button.tsx

- package-lock.json
- src/components/sandbox/Sandbox.tsx
- src/routes/components/ProgressIndicator.tsx
Issue to fix: https://github.com/GovAlta/ui-components/issues/1527
> fix(#1527): progress indicator unable to exit after enter the full screen - Code review needed

- src/routes/components/TextArea.tsx
- src/routes/components/TextField.tsx
- src/routes/components/Tooltip.tsx
- src/routes/design-tokens/border-radius/BorderRadius.tsx
- src/routes/design-tokens/border-width/BorderWidth.tsx
- src/routes/design-tokens/color/Color.tsx
- src/routes/design-tokens/color/colors.json
- src/routes/design-tokens/icon-size/IconSize.tsx
- src/routes/design-tokens/opacity/Opacity.tsx
- src/routes/design-tokens/overview/Overview.tsx
- src/routes/design-tokens/shadow/Shadow.tsx
- src/routes/design-tokens/spacing/Spacing.tsx
- src/routes/get-started/GetStartedOverview.tsx
- src/routes/get-started/Roadmap.tsx
- src/routes/get-started/designers/UxDesigner.tsx
- src/routes/get-started/qa-testing/QATestingOverview.tsx
- src/routes/patterns/LayoutPage.tsx
- src/routes/support/Contribute.tsx
- src/routes/support/DropInHours.tsx
- src/routes/support/SupportOverview.tsx
> chore: content update

- src/routes/components/HeroBanner.tsx
> chore: content updates

- src/components/component-properties/ComponentProperties.tsx
- src/routes/components/Chip.tsx
- src/routes/components/Components.tsx
- src/routes/components/Dropdown.tsx
- src/routes/components/Notificationbanner.tsx
- src/routes/components/Radio.tsx
- src/routes/components/TextArea.tsx
- src/routes/components/TextField.tsx
Also removed snackbar link, and updated required properties on certain components.
> feat(#1537): Added required badge for component properties

- src/routes/components/Modal.tsx
- src/routes/components/ProgressIndicator.tsx
- src/utils/styling.ts
This PR is try to fix the error described on https://github.com/GovAlta/ui-components/issues/1533
> fix(#1533): sandbox - not scrollable after closing modal/spinner - code review needed

- src/routes/components/AllComponents.tsx
Follow up with https://github.com/GovAlta/ui-components-docs/pull/69/files to allow filtering components by tags[].
> fix: allow filter components by tags - Code review needed

- index.html
- package-lock.json
- package.json
- src/components/code-snippet/CodeSnippet.css
- src/components/code-snippet/CodeSnippet.tsx
Add show more/show less to long code snippet
https://github.com/GovAlta/ui-components/issues/1544
> feat(#1544): add 'show more' for code snippet - code review needed

- src/App.tsx
- src/routes/components/Components.tsx
- src/routes/components/FormStepper.tsx
- src/routes/components/Tabs.tsx
> feat(#1551): add tabs page - code review needed

- src/routes/components/Popover.tsx
Pop over code snippet is wrong (missing target slot)
> fix(#1574): pop over code missing slot target - code review needed

- src/components/component-properties/ComponentProperties.tsx
- src/components/sandbox/Sandbox.css
- src/components/sandbox/Sandbox.tsx
- src/routes/components/Accordion.tsx
- src/routes/components/AllComponents.css
- src/routes/components/AppFooter.tsx
- src/routes/components/AppHeader.tsx
- src/routes/components/Button.tsx
- src/routes/components/Container.tsx
- src/routes/components/Details.tsx
- src/routes/components/FormStepper.tsx
- src/routes/components/IconButton.tsx
- src/routes/components/Icons.tsx
- src/routes/components/List.tsx
- src/routes/components/Modal.tsx
- src/routes/components/Table.tsx
- src/routes/components/TextArea.tsx
- src/routes/components/TextField.tsx
- src/routes/components/_template.tsx
Adjust the spacing between components example "h3", code sandbox and between examples. 
https://github.com/GovAlta/ui-components/issues/1575
> chore(#1575): adjust components examples padding - Code review needed

- src/App.tsx
- src/components/code-snippet/CodeSnippet.tsx
- src/components/component-properties/ComponentProperties.tsx
- src/components/sandbox/AngularReactiveSerializer.ts
- src/components/sandbox/AngularSerializer.ts
- src/components/sandbox/ComponentBinding.ts
- src/components/sandbox/Sandbox.tsx
- src/components/sandbox/SandboxProperties.tsx
- src/examples/accordion/AccordionExamples.tsx
- src/examples/accordion/accordion-example.css
- src/routes/components/Accordion.tsx
- tsconfig.json
- vite.config.ts
Accordion example: [Figma Link](https://www.figma.com/file/aeIJGExcpx9ecqnIVwImi1/Component-Pages?type=design&node-id=1-47334&mode=dev)
> feat(#1542): add accordion examples - code review needed

- src/components/sandbox/Sandbox.css
- src/examples/container/ContainerExamples.tsx
- src/examples/container/container-example.css
- src/routes/components/Container.tsx
- src/routes/get-started/developers/DevelopersSetup.tsx
- src/routes/patterns/LayoutPage.tsx
Add container examples. 
Design is at: https://www.figma.com/file/aeIJGExcpx9ecqnIVwImi1/Component-Pages?type=design&node-id=1-47354&mode=dev
> Feat/container examples - code review needed

- src/routes/components/Modal.tsx
For Modal component, add support for the closable property in the Sandbox. Then, when the closable checkbox is checked, modal should display the close icon. When it is unchecked then provide buttons to hide the modal b/c otherwise there will be no way to close the modal. In the generated code section, display the closable property for Angular. But for React, hide this.
> fix(#1618): modal,closable prop,add for Angular,remove for React

- package-lock.json
- package.json
- src/routes/components/FormItemPage.tsx
Documentation changes for the slotted helptext and error.
package.json
```
"@abgov/react-components": "4.17.0-alpha.28",
"@abgov/web-components": "1.17.0-alpha.56",
```
package-lock.json was also updated by running "npm install"
-Added 'slot' to both the props under Properties section (For Angular).
-Added ReactNode to both props (For React) 
-Added exmaples, one each for slotted helptext and slotted error (For Angular).
-Added React examples also with ReactNode fragments (For React) 
Below is a quick reference for examples on the usage.
This is the PLAIN TEXT example:
REACT
```
<GoAFormItem label="First name" helpText="This help text is in regular font plain-text">
<GoAInput name="firstName" ..... ></GoAInput>
</GoAFormItem>
```
ANGULAR
```
<goa-form-item label="First name" …
```
> fix(#1814): form item slotted error and helptext documentation

- src/routes/components/HeroBanner.tsx
Fixing https://github.com/GovAlta/ui-components/issues/1571
> fix(#1751): update hero banner code example

- package-lock.json
- package.json
- src/routes/components/Radio.tsx
Add aria-label to radio-item, following the pull request https://github.com/GovAlta/ui-components/pull/1899
> chore(#1859): add aria label for radio-item 

- package-lock.json
- package.json
- src/routes/components/Components.tsx
- src/routes/design-tokens/DesignTokenLayout.tsx
- src/routes/patterns/PatternsLayout.tsx
> bug/2017: fix side menu - need extra right padding

- src/routes/components/FormStepper.tsx
> chore/1647: fix form stepper sandbox

- src/routes/components/Pagination.tsx
Associated PR https://github.com/GovAlta/ui-components/pull/1997
1. Add examples for angular and react that allows using a dropdown to change the number of items per page. Users can copy-paste and run this code snippet. 
2. Replace the textbox with a dropdown, screenshot below
When the user copy pastes the code, the output will be like the screenshot below:
--------------------------------------------------------
**Angular Code**
--------------------------------------------------------
**ts**
```
import { Component } from "@angular/core";
import { faker } from "@faker-js/faker";
interface User {
id: string;
firstName: string;
lastName: string;
age: number;
}
@Component({
selector: "abgov-paginate",
templateUrl: "./paginate.html",
})
export class PaginateComponent {
users: User[] = []; …
```
> fix(#1680): docs add pagination examples with dropdown

- src/routes/components/Pagination.tsx
A new Sandbox example along with the code snippet has been added.
> fix(#1680): docs add a new pagination example with dropdown

- package-lock.json
- package.json
- src/examples/dropdown/DropdownExamples.tsx
- src/routes/components/Dropdown.tsx
Add `mount` and `mountType` to `Dropdown` properties
Add example
> chore(#1980): add mount property to dropdown and its example

- src/routes/components/Callout.tsx
> fix(#2029): docs callout add arialive prop

- src/routes/components/Tabs.tsx
> fix(#1665): docs tabs add onChange event

- src/routes/components/Icons.tsx
> fix(#1931): docs icon documentation update

- src/components/support-info/SupportInfo.tsx
- src/routes/home.tsx
- src/routes/root.tsx
- src/routes/support/SupportOverview.tsx
This just includes the work done for the following story;
- https://github.com/GovAlta/ui-components/issues/2035
> Production Release - September 11 / 2024

- src/examples/text-field/TextFieldExamples.tsx
Fixes: https://github.com/GovAlta/ui-components/issues/2090
> Code example fixes - input component

- package-lock.json
- package.json
- src/components/sandbox/SandboxProperties.tsx
- src/examples/modal/ModalExamples.tsx
- src/routes/components/DatePicker.tsx
> feat(#2044): add datepicker disabled property

- src/routes/components/DatePicker.tsx
This PR depends on https://github.com/GovAlta/ui-components/pull/2093
PR covers
-date picker reset example
-relative prop added to the properties accordion
> fix(#2056): date picker misc docs updates

- src/App.tsx
- src/components/table-of-contents/toc.module.css
- src/routes/components/AllComponents.tsx
- src/routes/components/Components.tsx
- src/routes/content/ContentLayout.tsx
- src/routes/design-tokens/DesignTokenLayout.tsx
- src/routes/get-started/GetStartedLayout.tsx
- src/routes/patterns/PatternsLayout.tsx
- src/routes/root.css
- src/routes/root.tsx
- src/routes/support/SupportLayout.tsx
- Removed section title from side menu on all sections
- adjusted max width to match design
- adjusted side menu padding to match design
- moved input in component grid to correct order (alphabetically)
- other small site fixes
> Small layout fixes and side menu update

- package-lock.json
- package.json
- src/routes/components/AppHeader.tsx
- src/routes/components/SideMenu.tsx
Following up with this PR https://github.com/GovAlta/ui-components/pull/2174/commits
> Feat/2162 & 2177 document

- src/examples/dropdown/DropdownExamples.tsx
Update the **existing** documentation example (dynamic options)
Related to https://github.com/GovAlta/ui-components/issues/2114
Figma Url: https://www.figma.com/design/aeIJGExcpx9ecqnIVwImi1/Component-Pages?t=tskpTCe0RrQSgyDi-0
Figma Screenshot (for this example)
> fix(#2114): docs dropdown update existing example

- .env.tmpl
- README.md
This removes the `.env` file that was causing issues with Netlify's build process. This also updates the `README` to give instructions on how to test the Bug Report Form, also how to install the website locally.
> chore: Removed env file and updated README

- package-lock.json
- package.json
- src/examples/filter-chip/TableWithGlobalFiltersExample.tsx
- src/routes/components/Text.tsx
- src/routes/components/TextArea.tsx
- src/routes/get-started/Support.tsx
Document PR to follow up story https://github.com/GovAlta/ui-components/issues/2512
> fix(#2512): rename "as" attribute as "tag" for text

- src/routes/components/Table.tsx
update to example title and figma link
> chore: table page content

- src/App.tsx
- src/routes/get-started/ComponentLifecycle.tsx
- src/routes/get-started/GetStartedLayout.tsx
Created the Component Lifecycle page.
[Figma Design](https://www.figma.com/design/IeqrkkSdOjbBtWHLM02Wv1/Updates-to-DS-website-pages?node-id=491-156416&m=dev)
> feat(#2569): Added Component Lifecycle Page

- package-lock.json
- package.json
> fix: Updating package versions

- src/routes/components/MicrositeHeader.tsx
PR: https://github.com/GovAlta/ui-components/issues/2341
> fix(#2341): docs microsite header prop fix camel case

- package-lock.json
- package.json
- src/components/version-language-switcher/HelpButton.tsx
- src/components/version-language-switcher/VersionLanguageSwitcher.tsx
- src/components/version-language-switcher/version-language-switcher.css
Reverts GovAlta/ui-components-docs#436
> Revert "fix(#2779): remove non-required event handling from version switcher"

- package-lock.json
- package.json
- src/components/sandbox/SandboxProperties.tsx
- src/components/version-language-switcher/HelpButton.tsx
- src/components/version-language-switcher/VersionLanguageSwitcher.tsx
- src/components/version-language-switcher/version-language-switcher.css
- src/routes/components/Components.tsx
- src/routes/components/MenuButton.tsx
- src/versioned-router.tsx
Added documentation for the Menu Button component, also updated the framework and version switcher in the Microsite Header to work with the new release of components.
> feat(#2779): Added Menu Button documentation

- package-lock.json
- package.json
- src/routes/components/MenuButton.tsx
Updated the Figma Link for the Menu Button component.
Also updated component versions to resolve Menu Button tertiary `type` background-color issue.
> fix: Updated Figma Link for Menu Button
